package cn.com.andiOs.entry.rbac;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.stereotype.Component;

/**
 * Model class of 权限详情表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Component
@Entity
public class Access implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue
	private Integer id;

	/** title. */
	@Column(name="title",columnDefinition = "varchar(50) DEFAULT '' NOT NULL COMMENT 'title : 权限名称'",  nullable=false, unique = false)
	private String title;

	/** urls. */	
	@Column(name="urls",columnDefinition = "varchar(1000) DEFAULT '' NOT NULL COMMENT 'urls : json 数组'",  nullable=false, unique = false)
	private String urls;

	/** status. */	
	@Column(name="status",columnDefinition = "tinyint(1) DEFAULT 1 NOT NULL COMMENT 'status : 状态 1：有效 0：无效'",  nullable=false, unique = false)
	private Byte status;

	/** udated_time. */	
	@Column(name="udatedTime",columnDefinition = "timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'udated_time : 最后一次更新时间'",  nullable=false, unique = false)
	private Date udatedTime;

	/** created_time. */	
	@Column(name="createdTime",columnDefinition = "timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'created_time : 插入时间'",  nullable=false, unique = false)
	private Date createdTime;

	/**
	 * Constructor.
	 */
	public Access() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the urls.
	 * 
	 * @param urls
	 *            urls
	 */
	public void setUrls(String urls) {
		this.urls = urls;
	}

	/**
	 * Get the urls.
	 * 
	 * @return urls
	 */
	public String getUrls() {
		return this.urls;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * Get the status.
	 * 
	 * @return status
	 */
	public Byte getStatus() {
		return this.status;
	}

	/**
	 * Set the udated_time.
	 * 
	 * @param udatedTime
	 *            udated_time
	 */
	public void setUdatedTime(Date udatedTime) {
		this.udatedTime = udatedTime;
	}

	/**
	 * Get the udated_time.
	 * 
	 * @return udated_time
	 */
	public Date getUdatedTime() {
		return this.udatedTime;
	}

	/**
	 * Set the created_time.
	 * 
	 * @param createdTime
	 *            created_time
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * Get the created_time.
	 * 
	 * @return created_time
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Access other = (Access) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
