package cn.com.andiOs.entry.rbac;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.stereotype.Component;

/**
 * Model class of 角色权限表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Component
@Entity
public class RoleAccess implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue
	private Integer id;

	/** roleId. */
	@Column(name="roleId",columnDefinition = "int(11) DEFAULT 0 NOT NULL COMMENT 'roleId : 角色Id'",  nullable=false, unique = false)
	private Integer roleId;

	/** access_id. */
	@Column(name="accessId",columnDefinition = "int(11) DEFAULT 0 NOT NULL COMMENT 'access_id : 权限id'",  nullable=false, unique = false)
	private Integer accessId;

	/** created_time. */
	@Column(name="createdTime",columnDefinition = "timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'created_time : 插入时间'",  nullable=false, unique = false)
	private Date createdTime;

	/**
	 * Constructor.
	 */
	public RoleAccess() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the roleId.
	 * 
	 * @param roleid
	 *            roleId
	 */
	public void setRoleid(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * Get the roleId.
	 * 
	 * @return roleId
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * Set the access_id.
	 * 
	 * @param accessId
	 *            access_id
	 */
	public void setAccessId(Integer accessId) {
		this.accessId = accessId;
	}

	/**
	 * Get the access_id.
	 * 
	 * @return access_id
	 */
	public Integer getAccessId() {
		return this.accessId;
	}

	/**
	 * Set the created_time.
	 * 
	 * @param createdTime
	 *            created_time
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * Get the created_time.
	 * 
	 * @return created_time
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		RoleAccess other = (RoleAccess) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
