package io.github.bigCloudAi.entry.rbac;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.stereotype.Component;

/**
 * Model class of 用户操作记录表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Component
@Entity
public class AppAccessLog implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue
	private Integer id;

	/** uid. */
	@Column(name="uid",columnDefinition = "int(20) DEFAULT 0 NOT NULL COMMENT 'uid : 品牌UID'",  nullable=false, unique = false)
	private Long uid;

	/** target_url. */
	@Column(name="targetUrl",columnDefinition = "varchar(255) DEFAULT '' NOT NULL COMMENT 'target_url : 访问的url'",  nullable=false, unique = false)
	private String targetUrl;

	/** query_params. */
	@Column(name="queryParams",columnDefinition = "clob NOT NULL COMMENT 'query_params : get和post参数'",  nullable=false, unique = false)
	private String queryParams;

	/** ua. */
	@Column(name="ua",columnDefinition = "varchar(255) DEFAULT '' NOT NULL COMMENT 'ua : 访问ua'",  nullable=false, unique = false)
	private String ua;

	/** ip. */
	@Column(name="ip",columnDefinition = "varchar(32) DEFAULT '' NOT NULL COMMENT 'ip : 访问ip'",  nullable=false, unique = false)
	private String ip;

	/** note. */
	@Column(name="note",columnDefinition = "varchar(1000) DEFAULT '' NOT NULL COMMENT 'note : json格式备注字段'",  nullable=false, unique = false)
	private String note;

	/** created_time. */
	@Column(name="createdTime",columnDefinition = "timestamp DEFAULT NOW() NOT NULL COMMENT 'created_time'",  nullable=false, unique = false)
	private Date createdTime;

	/**
	 * Constructor.
	 */
	public AppAccessLog() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the uid.
	 * 
	 * @param uid
	 *            uid
	 */
	public void setUid(Long uid) {
		this.uid = uid;
	}

	/**
	 * Get the uid.
	 * 
	 * @return uid
	 */
	public Long getUid() {
		return this.uid;
	}

	/**
	 * Set the target_url.
	 * 
	 * @param targetUrl
	 *            target_url
	 */
	public void setTargetUrl(String targetUrl) {
		this.targetUrl = targetUrl;
	}

	/**
	 * Get the target_url.
	 * 
	 * @return target_url
	 */
	public String getTargetUrl() {
		return this.targetUrl;
	}

	/**
	 * Set the query_params.
	 * 
	 * @param queryParams
	 *            query_params
	 */
	public void setQueryParams(String queryParams) {
		this.queryParams = queryParams;
	}

	/**
	 * Get the query_params.
	 * 
	 * @return query_params
	 */
	public String getQueryParams() {
		return this.queryParams;
	}

	/**
	 * Set the ua.
	 * 
	 * @param ua
	 *            ua
	 */
	public void setUa(String ua) {
		this.ua = ua;
	}

	/**
	 * Get the ua.
	 * 
	 * @return ua
	 */
	public String getUa() {
		return this.ua;
	}

	/**
	 * Set the ip.
	 * 
	 * @param ip
	 *            ip
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * Get the ip.
	 * 
	 * @return ip
	 */
	public String getIp() {
		return this.ip;
	}

	/**
	 * Set the note.
	 * 
	 * @param note
	 *            note
	 */
	public void setNote(String note) {
		this.note = note;
	}

	/**
	 * Get the note.
	 * 
	 * @return note
	 */
	public String getNote() {
		return this.note;
	}

	/**
	 * Set the created_time.
	 * 
	 * @param createdTime
	 *            created_time
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * Get the created_time.
	 * 
	 * @return created_time
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		AppAccessLog other = (AppAccessLog) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
