package io.github.bigCloudAi.entry.rbac;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.springframework.stereotype.Component;

/**
 * Model class of 用户角色表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Component
@Entity
public class UserRole implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	@Id
	@GeneratedValue
	private Integer id;

	/** uid. */
	@Column(name="uid",columnDefinition = "int(11) DEFAULT 0 NOT NULL COMMENT 'uid : 用户id'",  nullable=false, unique = false)
	private Integer uid;

	/** role_id. */
	@Column(name="roleId",columnDefinition = "int(11) DEFAULT 0 NOT NULL COMMENT 'role_id : 角色ID'",  nullable=false, unique = false)
	private Integer roleId;

	/** created_time. */
	@Column(name="createdTime",columnDefinition = "timestamp DEFAULT '0000-00-00 00:00:00' NOT NULL COMMENT 'created_time'",  nullable=false, unique = false)
	private Date createdTime;

	/**
	 * Constructor.
	 */
	public UserRole() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the uid.
	 * 
	 * @param uid
	 *            uid
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * Get the uid.
	 * 
	 * @return uid
	 */
	public Integer getUid() {
		return this.uid;
	}

	/**
	 * Set the role_id.
	 * 
	 * @param roleId
	 *            role_id
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * Get the role_id.
	 * 
	 * @return role_id
	 */
	public Integer getRoleId() {
		return this.roleId;
	}

	/**
	 * Set the created_time.
	 * 
	 * @param createdTime
	 *            created_time
	 */
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	/**
	 * Get the created_time.
	 * 
	 * @return created_time
	 */
	public Date getCreatedTime() {
		return this.createdTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserRole other = (UserRole) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
